### PR TITLE
Add more type hinting to the classes and fix a typo in the CurrentProcessesPerQueue class name

### PR DESCRIPTION
**Pull request by thisismahabadi**
There was a typo on this class CurrentProccesesPerQueue so I replaced it with CurrentProcessesPerQueue.

Also added some more type hinting to different methods.

### CODE REVIEW

**Comment by thisismahabadi** [comment]
LMK what you think @LKaemmerling

**Comment by thisismahabadi** [comment]
Another ping @LKaemmerling

**Comment by LKaemmerling** [comment]
Thank you @thisismahabadi !

**Comment by smitmartijn** [comment]
Awesome people maintaining this project, ignore this comment. Just FYI for anyone who gets to this PR like me, googling the error about "CurrentProccesesPerQueue" not being defined: this PR was a breaking change if you had the old typo'd `CurrentProccesesPerQueue` in your `config/horizon-exporter.php` in the `exporters` array. Rename it to the new `CurrentProcessesPerQueue` and you'll be good. 😊

**Pull request merged**
