### PR TITLE
add recent jobs metrics

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by LKaemmerling** [comment]
First of all, thank you! Could you name it like `RecentJobs`? `AllJobs` sounds a bit misleading.

**Comment by ghost** [comment]
> First of all, thank you! Could you name it like `RecentJobs`? `AllJobs` sounds a bit misleading.

Yup, I updated the name and pushed again.

**Comment by LKaemmerling** [comment]
Perfect! Thank you!

**Comment by LKaemmerling** [comment]
@jose116 released as v1.1.0. I have renamed the metric to `<namespace>_horizon_recent_jobs`

**Pull request merged**
